apiVersion: apps/v1
kind: Deployment
metadata: 
  name: c2
  namespace:  newapp-ns
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/jduimovich0/bootstrap
        name: container-image  
